### ISSUE TITLE
installing biotradis on MacOS

### ISSUE THREAD

**Issue by angelovangel** [sanger-pathogens/Bio-Tradis#110]
Hi there,
I am having issues installing Bio-Tradis using conda on MacOS. I have added the channels. Am I missing something?
Thanks!

````
PackagesNotFoundError: The following packages are not available from current channels:

  - biotradis

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
```

**Comment by sbastkowski** [comment]
Hi,
I enabled installation on macOS. You can run:
conda install -c bioconda biotradis

There might be an issue with the samtools. If you encounter this you need to manually change the version by running 
conda install -c bioconda samtools=1.9=h8ee4bcc_1

Let me know if that works.

**Comment by angelovangel** [comment]
Thanks a lot! Bio-Tradis installs OK, but some perl modules are not found (although they are installed)
For example:
```

(base) Angels-MBP:~ angelangelov$ bacteria_tradis -h
Can't locate Exception/Class.pm in @INC (you may need to install the Exception::Class module) (@INC contains: /anaconda3/bin/../lib/ /software/pathogen/internal/prod/lib/ ./lib ../lib /anaconda3/lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /anaconda3/bin/../lib/Bio/Tradis/Exception.pm line 12.
BEGIN failed--compilation aborted at /anaconda3/bin/../lib/Bio/Tradis/Exception.pm line 14.
Compilation failed in require at /anaconda3/bin/../lib/Bio/Tradis/RunTradis.pm line 64.
BEGIN failed--compilation aborted at /anaconda3/bin/../lib/Bio/Tradis/RunTradis.pm line 64.
Compilation failed in require at /anaconda3/bin/../lib/Bio/Tradis/CommandLine/TradisAnalysis.pm line 15.
BEGIN failed--compilation aborted at /anaconda3/bin/../lib/Bio/Tradis/CommandLine/TradisAnalysis.pm line 15.
Compilation failed in require at /anaconda3/bin/bacteria_tradis line 21.
BEGIN failed--compilation aborted at /anaconda3/bin/bacteria_tradis line 21.
```
But `Exception::Class` is there:
```
(base) Angels-MBP:~ angelangelov$ cpanm Exception::Class
Exception::Class is up to date. (1.44)
```

**Comment by sbastkowski** [comment]
Hi again,
this looks like a specific error to your system. You could try to find the location of the Exception/Class.pm (run: find ~/ -type f -name "Class.pm") and see if the direction is on the path if not, try to install it to one of the path locations (@INC contains: /anaconda3/bin/../lib/ /software/pathogen/internal/prod/lib/ ./lib ../lib /anaconda3/lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18).

**Comment by angelovangel** [comment]
Thank you!
Anyway, you are right, it seems it is an error specific to my system. As biotradis installs OK on a Mac with conda, I think this closes the issue.
Best,
