### ISSUE TITLE
Error in step 3.5 of bacteria_tradis, using samtools 1.3

### ISSUE THREAD

**Issue by juanu** [sanger-pathogens/Bio-Tradis#63]
When using samtools 1.3, there is an error in step 3.5 of the bacteria_tradis pipeline. The error is:

> ..........Step 3.5: Convert output from SAM to BAM and sort
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files

This seems to be due to changes in the samtools options (https://github.com/samtools/samtools/releases/tag/1.3):

> obsolete samtools sort in.bam out.prefix usage has been removed. If you are still using ‑f, ‑o, or out.prefix, convert to use -T PREFIX and/or -o FILE instead. (#295, #349, #356, #418, PR #441; see also discussions in #171, #213.)

**Comment by andrewjpage** [comment]
Support has just been added to allow for the samtools 1.3 syntax changes. Thanks for submitting the bug report
