### ISSUE TITLE
tradis_comparison.R error

### ISSUE THREAD

**Issue by DanMediati** [sanger-pathogens/Bio-Tradis#71]
Hello, I keep getting the "error unexpected input in _". I don't see an underscore at the beginning of an argument or option and I've tried surrounding the names with backticks but to no avail. 

danielmediati$ tradis_comparison.R -o outputfile.csv -p outputplot.pdf --controls controlsLB.txt --conditions conditionsM9.txt 
Loading required package: limma
Read 2 items
Read 2 items
Error: unexpected input in "_"
Execution halted

Im concerned because the script is able to generate and produce both output files, that being the "output file.csv" and the "output plot.pdf", are these files accurately constructed despite the error occurring? Has this issue happened to anyone else and if so how was this resolved?

Cheers for any help/advice

**Comment by lbarquist** [comment]
For posterity's sake: this is due to POD documentation lines that are added during the system installation of these scripts, possibly due to handling by cpan? These do not affect the results of these scripts, but should be fixed.

**Comment by andrewjpage** [comment]
Thanks for letting us know. I've updated the CPAN module so that it doesnt add PERL documentation lines to the bottom of R scripts!  Version 1.3.1 should be available from CPAN in the next few hours.
