### ISSUE TITLE
cpan update?

### ISSUE THREAD

**Issue by lbarquist** [sanger-pathogens/Bio-Tradis#75]
Hi,

I've just noticed the version of tradis_essentiality.R we're distributing via github and cpan are out of synch -- it looks like it's still the old version on cpan. So, anyone following our installation recommendations will be getting an out of date version. Would it be possible to synch the two?

Thanks,
Lars

**Comment by andrewjpage** [comment]
I've uploaded a new version. Should be indexed in the next few hours.
Andrew
