### ISSUE TITLE
Port 18 volume discrepancy?

### ISSUE THREAD

**Issue by ucpete** [sanger-pathogens/Bio-Tradis#83]
For the 10 cycle transposon chemistry, `C1` ("Custom 1 Primer Mix") has 300 µL and then 75 µL aspirated for the first sequencing read:

https://github.com/sanger-pathogens/Bio-Tradis/blob/master/recipes/Transposon10/Chemistry/Chemistry.xml#L303-L304

Another 300 µL + 75 µL are aspirated for the first index read:

https://github.com/sanger-pathogens/Bio-Tradis/blob/master/recipes/Transposon10/Chemistry/Chemistry.xml#L326-L327

Yet the protocol in the supplement of the manuscript describes a loading of only 608 µL total into port 18 on a MiSeq:

![image](https://user-images.githubusercontent.com/943217/33642209-b415e626-d9ed-11e7-9b5e-5f57ef4f1a3e.png)

Am I misunderstanding the sequencing and chemistry protocol, or would this not lead to insufficient volume of `C1` being loaded for the run (750 µL > 608 µL)? Is there a typo in the sequencing recipe, or should we just make up say 800 µL of HT1 + primer for `C1` / port 18?

Thank you!

**Comment by lbarquist** [comment]
Hi,

I've been in touch with Matt Mayho who did most of the development on the sequencing protocols, and he's in touch with the folks at Illumina that helped us develop the recipe -- we should have a full response for you sometime next week. In the meantime here's what Matt had to say:

"I would say the comment sounds correct and therefore it makes sense to add 800ul (keeping the final primer concentration the same).  Because we've done many MiSeq TraDIS runs and they work fine I assume the lack of primer volume hasn't had a major effect."

**Comment by ucpete** [comment]
Thanks for the speedy response @lbarquist!

I'm glad to hear that it's never been an issue, and I've relayed to my experimental collaborators that we should go ahead and prepare 800 µL of equal concentration `C1` volume. I look forward to hearing the explanation – if there really is insufficient volume (but it works out anyway because primer is always in excess), if the volumes I'm interpreting as being aspirated twice are somehow not cumulative or fully dispensed, or if there's another explanation beyond my understanding after careful reading of the protocol.

Thanks again,
peter

**Comment by ucpete** [comment]
Hey, I know folks are taking off for vacation (or are already gone), but I'm just curious if anyone heard back from Illumina on this.

Our first attempt at the 10 dark cycle protocol on the MiSeq went poorly. We scaled up to 800 µL of primer mix on port 18, and while the volume wasn't completely exhausted post-run, we got almost no sequences from libraries other than phiX (99.99% of sequences fell into the `Undetermined` index bin). The low cluster  density we observed as well suggests that either our (custom) libraries never bound to the flow cell in the first place, or if they did, something went awry during sequence primer annealing.

I'm positive the failure has _nothing_ to do with the port 18 volume question – we had leftover volume, and primer is likely an order of magnitude or more in excess anyway – but it would be good to rule out completely as we troubleshoot. I've suggested to my colleagues that they clone and Sanger sequence a small amount of the library (a few dozen clones' worth) to check that our library amplicons have the expected topology, and that our primer binding sites and indices are exactly the sequences we expect.

We'll be trying again in the new year – even if we don't hear back, I'm sure we'll figure it out given other folks are using the same strategy and recipes successfully. Thanks again, and happy holidays!

**Comment by lbarquist** [comment]
Hi Peter,

Sorry to hear about your troubles. I've pinged Matt again to see if he's heard back re: the volumes, and will try to get back to you soon. You can email me at lars.barquist@uni-wuerzburg.de if you continue having troubles with the library prep and I can put you in touch with some people that might be able to help.

-Lars

**Comment by lbarquist** [comment]
Hi Peter,

I heard back from Matt, here's what he had to say:

"I did speak to our Illumina FAS and he agrees that we should ideally be adding 800ul.  It was a small oversight when he wrote the recipe that none of us noticed the volume discrepency!  However, its never noticably had any effect, probably bacause the bilk of that volume goes to fill all the lines and there's only a very small fraction of this on the flow cell - obviously 600ul is sufficient to fill most of the lines plus flow cell.

Regarding the comments of the failed TradIS runs - so its sounds the run proceeded at least and PhiX was sequenced, but there was an issue with the TradIS part of the sequencing.  in trying to diagnose this i'd like to check:

Was the sample sheet correctly filled out ? - i think we have an example in our paper.  If they send us theirs we can check this.

Did the qPCR give good results - qPCR with sequencing primer + P7 primer being slightly less in value than qPCR with P5+P7 primers?

Is the Tm of the sequencing primer sufficiently high?

Does the Transposon specific PCR primer have the correct P5 sequence?

Is the P7 indexed adapter primer ok?"

Maybe it'd be best to close the ticket & continue the discussion over email, that way we can loop Matt in directly - he'll be more useful than me for troubleshooting the library prep & sequencing protocols.

-Lars

**Comment by ucpete** [comment]
@lbarquist – Thanks a lot!

Yes, please close this ticket. The 'fix' here isn't really something for which I can submit an obvious PR, as the advice is to keep the recipes as they are and to instead make up more primer mix, but that volume is detailed in the Supp. Methods of the paper, not hosted on GitHub.

Though you may consider adding a comment or some sort of README in the repository, or maybe even adding the (slightly tweaked) methods to the repository as well. I'll of course leave that decision of how to handle it (if at all) up to you guys, but I'm happy to throw together a fix and submit a PR if that would help. Writing this out, I think simply adding a revised version of the bench methods here might be best.

My experimental colleagues sequenced some of their library via Sanger sequencing, and have informed me that their Tn-specific primer was too short, so they have redesigned it and will try again come February (January is booked for them already). I will follow up by email once they've given it another shot, and hope that it's just to report good news!

Thanks again for your help, it's much appreciated,
peter
